# Generated by Django 3.1.7 on 2021-04-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210405_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_name',
            field=models.CharField(max_length=256, verbose_name='Имя клиента'),
        ),
    ]
