# Generated by Django 3.1.7 on 2021-04-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210405_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_login',
            field=models.CharField(blank=True, max_length=128, verbose_name='Логин телеграм'),
        ),
    ]
