# Generated by Django 3.1.7 on 2021-04-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_telegram_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='telegram_login',
            new_name='telegram',
        ),
    ]
