# Generated by Django 3.1.7 on 2021-04-07 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_user_telegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterRequest',
            fields=[
                ('master_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.master')),
            ],
            bases=('app.master',),
        ),
    ]
