# Generated by Django 3.1.7 on 2021-04-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_masterrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterrequest',
            options={'verbose_name': 'Заявка на мастера', 'verbose_name_plural': 'Заявки на мастеров'},
        ),
        migrations.AddField(
            model_name='master',
            name='telegram_chat_id',
            field=models.CharField(default='11111', max_length=128),
        ),
    ]
