# Generated by Django 3.1.7 on 2021-04-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210407_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
