# Generated by Django 3.1.7 on 2021-04-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210407_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Индентефикатор чата телеграм'),
        ),
    ]
