# Generated by Django 3.1.7 on 2021-04-08 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210407_2247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Master',
            new_name='TelegramMaster',
        ),
    ]
