# Generated by Django 3.1.7 on 2021-04-08 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210408_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', related_query_name='order', to='app.telegrammaster'),
        ),
    ]
