# Generated by Django 3.1.7 on 2021-04-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210408_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammaster',
            name='telegram',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Телеграм'),
        ),
    ]
