# Generated by Django 3.1.7 on 2021-04-08 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210408_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='master_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_request', related_query_name='order_request', to='app.telegrammaster'),
        ),
    ]
