# Generated by Django 3.1.7 on 2021-04-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_order_master_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='master_request',
        ),
        migrations.AddField(
            model_name='order',
            name='master_requests',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders_request', related_query_name='order_request', to='app.TelegramMaster'),
        ),
    ]
