# Generated by Django 3.1.7 on 2021-04-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_order_master_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_waiting_for_master',
            field=models.BooleanField(default=False, verbose_name='Ожидает подтвержения мастера'),
        ),
    ]
