# Generated by Django 3.1.7 on 2021-04-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_order_is_waiting_for_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_waiting_for_master',
        ),
        migrations.AddField(
            model_name='order',
            name='master_request',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders_request', related_query_name='order_request', to='app.TelegramMaster'),
        ),
    ]
