# Generated by Django 3.1.7 on 2021-04-08 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210408_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='master',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_accepted': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', related_query_name='order', to='app.telegrammaster'),
        ),
        migrations.AlterField(
            model_name='order',
            name='master_request',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_accepted': True}, null=True, related_name='orders_request', related_query_name='order_request', to='app.TelegramMaster'),
        ),
    ]
