# Generated by Django 3.1.7 on 2021-04-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20210409_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='master_request',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_accepted': True}, related_name='orders_request', related_query_name='order_request', to='app.TelegramMaster'),
        ),
    ]
