# Generated by Django 3.1.7 on 2021-04-09 19:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20210409_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='working_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 20, 3, 9, 23218, tzinfo=utc), verbose_name='Когда начинать работу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='master_request',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_accepted': True}, related_name='orders_request', related_query_name='order_request', to='app.TelegramMaster', verbose_name='Предложения мастерам'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('R', 'Готово'), ('W', 'Ждет'), ('C', 'Отменен'), ('J', 'В работе'), ('M', 'Модернизация')], default='W', max_length=1, verbose_name='Статус'),
        ),
    ]
