# Generated by Django 3.1.7 on 2021-04-10 18:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20210410_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='master_request',
            new_name='master_requests',
        ),
        migrations.AlterField(
            model_name='order',
            name='working_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 19, 27, 21, 501426, tzinfo=utc), verbose_name='Когда начинать работу'),
        ),
    ]
