# Generated by Django 3.1.7 on 2021-04-10 18:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20210410_2339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramprofile',
            options={'verbose_name': 'Телеграм аккаунт', 'verbose_name_plural': 'Телеграм аккаунты'},
        ),
        migrations.AlterField(
            model_name='order',
            name='working_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 19, 40, 48, 125465, tzinfo=utc), verbose_name='Когда начинать работу'),
        ),
    ]
