# Generated by Django 3.1.7 on 2021-04-12 18:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20210411_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='master',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_master': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', related_query_name='order', to='app.telegramprofile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='master_requests',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_master': True}, related_name='orders_request', related_query_name='order_request', to='app.TelegramProfile', verbose_name='Предложения мастерам'),
        ),
        migrations.AlterField(
            model_name='order',
            name='working_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 12, 19, 34, 6, 183850, tzinfo=utc), verbose_name='Когда начинать работу'),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='telegram_chat_id',
            field=models.CharField(max_length=128, unique=True, verbose_name='Telegram id чата'),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='telegram_first_name',
            field=models.CharField(max_length=128, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='telegram_last_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Фамилия'),
        ),
    ]
