# Generated by Django 3.1.7 on 2021-04-13 19:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20210413_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='working_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 13, 20, 8, 50, 4115, tzinfo=utc), verbose_name='Когда начинать работу'),
        ),
    ]
