# Generated by Django 3.1.7 on 2021-04-13 19:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20210414_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='master_requests',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_master': True}, null=True, related_name='orders_request', related_query_name='order_request', to='app.TelegramProfile', verbose_name='Предложения мастерам'),
        ),
        migrations.AlterField(
            model_name='order',
            name='working_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 13, 20, 10, 58, 801755, tzinfo=utc), verbose_name='Когда начинать работу'),
        ),
    ]
