# Generated by Django 3.1.7 on 2021-04-14 12:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20210414_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='announced_amounts',
            field=models.TextField(blank=True, default='', verbose_name='Цены озвучены'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_adress',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_city',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_phone',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Телефон клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='working_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 14, 13, 2, 52, 778881, tzinfo=utc), verbose_name='Когда начинать работу'),
        ),
    ]
