# Generated by Django 3.1.7 on 2021-04-14 12:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20210414_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='master',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_master': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', related_query_name='order', to='app.telegramprofile', verbose_name='ВМ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='master_advert_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Рекламное имя ВМ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='master_requests',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_master': True}, null=True, related_name='orders_request', related_query_name='order_request', to='app.TelegramProfile', verbose_name='Предложения ВМ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='working_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 14, 13, 4, 30, 560475, tzinfo=utc), verbose_name='Когда начинать работу'),
        ),
    ]
