# Generated by Django 3.1.7 on 2021-04-14 12:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20210414_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Проблема'),
        ),
        migrations.AlterField(
            model_name='order',
            name='working_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 14, 13, 53, 37, 710100, tzinfo=utc), verbose_name='Когда начинать работу'),
        ),
    ]
