# Generated by Django 3.1.7 on 2021-04-15 17:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20210414_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Город')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='master_requests',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_master': True}, related_name='orders_request', related_query_name='order_request', to='app.TelegramProfile', verbose_name='Предложения ВМ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='working_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 15, 18, 49, 54, 155581, tzinfo=utc), verbose_name='Когда начинать работу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_city', related_query_name='client_cities', to='app.city', verbose_name='Город'),
        ),
    ]
