# Generated by Django 3.1.7 on 2021-04-15 17:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20210415_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='working_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 15, 18, 55, 24, 126903, tzinfo=utc), verbose_name='Когда начинать работу'),
        ),
    ]
