# Generated by Django 3.1.7 on 2021-04-18 17:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20210416_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='working_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 18, 18, 39, 27, 695710, tzinfo=utc), verbose_name='Когда начинать работу'),
        ),
    ]
