# Generated by Django 3.1.7 on 2021-04-18 17:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20210418_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='percents',
            field=models.TextField(default='0-2999%35,3000-999999%50', help_text='[от-до%процент, от-до%процент...]', max_length=512, verbose_name='Проценты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='working_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 18, 18, 58, 0, 464555, tzinfo=utc), verbose_name='Когда начинать работу'),
        ),
    ]
