# Generated by Django 3.1.7 on 2021-04-18 19:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20210418_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='clear_amount',
            new_name='clear_amount_calculated',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='master_amount',
            new_name='master_amount_calculated',
        ),
        migrations.AlterField(
            model_name='order',
            name='working_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 18, 20, 30, 49, 517976, tzinfo=utc), verbose_name='Когда начинать работу'),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='percents',
            field=models.CharField(default='0-2999%35,3000-999999%50', help_text='[от-до%процент, от-до%процент...]. Если интервалы пересекаются, будет выбран первый в списке.', max_length=512, verbose_name='Проценты'),
        ),
    ]
