# Generated by Django 3.1.7 on 2021-04-18 19:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20210419_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='working_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 18, 20, 35, 19, 83285, tzinfo=utc), verbose_name='Когда начинать работу'),
        ),
    ]
