# Generated by Django 3.1.7 on 2021-04-19 12:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20210419_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cashed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Деньги собраны?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='working_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 19, 13, 44, 28, 447086, tzinfo=utc), verbose_name='Когда начинать работу'),
        ),
    ]
