# Generated by Django 3.2 on 2021-04-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20210419_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='working_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Когда начинать работу'),
        ),
    ]
