# Generated by Django 3.1.7 on 2021-04-19 13:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20210419_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cached_master_percent',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Процент мастера.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='working_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 19, 14, 15, 59, 12630, tzinfo=utc), verbose_name='Когда начинать работу'),
        ),
    ]
