# Generated by Django 3.1.7 on 2021-04-20 12:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20210419_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cached_master_percent',
            field=models.FloatField(blank=True, default=0, verbose_name='Процент мастера.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_city', related_query_name='client_cities', to='app.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='order',
            name='working_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 20, 13, 6, 28, 511842, tzinfo=utc), verbose_name='Когда начинать работу'),
        ),
    ]
