# Generated by Django 3.1.7 on 2021-04-20 12:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20210420_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата расхода')),
                ('spending_tupe', models.CharField(choices=[(0, 'Реклама оплата труда'), (1, 'Реклама материал'), (2, 'Реклама интернет'), (3, 'Зарплата Руководителя'), (4, 'Зарплата Подчиненых'), (5, 'Командировка'), (6, 'Аренда'), (7, 'Инкасация'), (8, 'Перенос с прошлого мес.')], default='Реклама оплата труда', max_length=1, verbose_name='Тип')),
                ('comment', models.TextField(blank=True, max_length=512, null=True, verbose_name='Комментарий')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='working_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 20, 13, 27, 9, 441888, tzinfo=utc), verbose_name='Когда начинать работу'),
        ),
    ]
