# Generated by Django 3.1.7 on 2021-04-20 12:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_auto_20210420_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spending',
            old_name='spending_tupe',
            new_name='spending_type',
        ),
        migrations.AlterField(
            model_name='order',
            name='working_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 20, 13, 59, 29, 741371, tzinfo=utc), verbose_name='Когда начинать работу'),
        ),
    ]
